### ISSUE TITLE
when using empty @build section, build-options is not used

### ISSUE THREAD

**Issue by jmichalon** [Lukc/pkgxx#16]

**Comment by jmichalon** [comment]
workaround (example):
export MAKEFLAGS='-j8'

**Comment by Lukc** [comment]
build-options is used by modules, and modules are not used if you add an empty `@build` section.

Since this looks like normal behavior, I’m closing this issue.

PS: You can export that variable in pkgxx.conf. Have a look at the example files if you need to know how.
